# Week 03 - Lists and Arrays

## Drill

What are the differences between `for` and `while` loop?

* `while` loop requires a counter initiated, if applicable. 
* `while` loop requires the counter to be increased explicitly. 
* `for` loop does not change the objects inside the loop back to outside. 

Write a code that will print a list of food names that starts with 'e' with less than 8 characters. The list is provided to you. 

In [ ]:
food_ls = ['egg', 'fish', 'eggplant', 'crab', 'tomato', 'bread', 'eel', 'milk', 'tea']
# Your code 


In [3]:
# Solution
food_ls = ['egg', 'fish', 'eggplant', 'crab', 'tomato', 'bread', 'eel', 'milk', 'tea']
for i in range(len(food_ls)): 
    if len(food_ls[i]) < 8 and food_ls[i][0] == 'e': 
        print(food_ls[i])

egg
eel


## List and Array

List and arrays are data types that collects a group of data. The main distinction between lists and arrays is how it is stored in the computer. In computers there is a concept called pointers. You can think it as the address of the data. 

* Lists collects different data types, while array collects the same data type as a group. 
* Lists allows sequential access, while array allows both sequential or direct access (sometimes it is faster in computation). 

## List

So let us start looking further into lists. Loops and lists are good companions. Like we said above, lists are only aceessed sequentially. So we mostly use loops to edit the list. For example, to see the elements in the list one by one, we do the following. 
```python
ls = [1, 5, 9, 10, 11]
for i in ls: 
    print(ls[i])
```

So let us start with printing different data types. In this course, we would use objects to store complex information. 

### Initialise a List

To create a list, the syntax is simply a square bracket with commas separating the elements. 
```python
a = [1, 'some sort of string']

for i in range(len(a)): 
    print('{} is in the list a'.format(a[i]))   # print elements in list a
```

__Exercise:__ Write a list that includes the shopping items that you can think of. 

In your code, just make sure you have initialise the list and use `print()` function afterwards. 

In [ ]:
# Your code here


## Access Elements

To access the elements, one will need to use a square bracket after the list. For example, 
```python
ls[0]
``` 
means to return the first element of the list. List elements starts with the index 0. We can see the structure of lists in the figure below. 

<img src="fig/ls.png"/>

In [1]:
# Demonstration
ls = [22, 35, -3, 9, 10, 11, 10]
ls[0]

1

To print out the last element, one will just needed to print the -1th element of the list. 

In [ ]:
# Demonstration
ls[-1]

<img src="fig/ls01.png"/>

### List Methods

What if we have the elements and needed to add into the list? The `append()` function would be helpful. This function will add the elements specified in the brackets. For example, we would like to append a new tweet into the list of tweets. Let's say the tweet object is called `new_tweet`. Then we would write 
```python
tweets.append(new_tweet)
```
and it will do the work. Of course, your list `tweets` should be defined beforehand. So if the list is empty at first, the code snippnet is 
```python
tweets = []
tweets.append(new_tweet)
```

So let us do some exercise at below: 

__Exercise:__ Write a code that will print the food that starts with `'s'`. The code will count how many food are included at the end of your code. 

In [ ]:
# Your code below
food = ['salad', 'sandwich', 'bread', 'steak', 'tuna steak', 'fish', 'rice', 'spaghetti']

In [2]:
# Solution
food = ['salad', 'sandwich', 'bread', 'steak', 'tuna steak', 'fish', 'rice', 'spaghetti']
s_food = []
for i in range(len(food)): 
    if food[i][0] == 's': 
        s_food.append(food[i])
print('There are {} food that starts with \'s\'.'.format(len(s_food)))

There are 4 food that starts with 's'.


If we wish to remove an element in a list, we use the `remove()` function. What the function does is to remove the element specified in the brackets. For example, 
```
animals = ['cat', 'dog', 'chicken', 'sheep', 'pig']
```
To remove sheep in the list, we say `animals.remove('sheep')`. So now there is no sheep in the animals list. Note the brackets for the removed element. 

__Exercise:__ Write a code that will remove `'pig'` from the list. 

In [ ]:
# Your code below
animals = ['cat', 'dog', 'chicken', 'sheep', 'pig']

In [ ]:
# Solution
animals = ['cat', 'dog', 'chicken', 'sheep', 'pig']
animals.remove('pig')

## Numpy Array

In Python there are no native arrays existed. We rely on numpy to import the concept of arrays. 

In [1]:
import numpy as np

Once we imported numpy, Python will then convert all lists in this notebook as numpy arrays. If one wishes to convert them back to the normal lists, they can abort the kernel to start everything again. 

The 2 main important functions in numpy are: 
* convert lists to arrays for efficient computation.
* perform elementwise computation

### Initialise numpy Array

To initialise a `numpy` array, we often create a pre-defined array and filled in the data. This is different to what we have said about initialising a list with appending elements. It is more efficient to create a pre-defined array with numpy. 

There are 3 functions (to date) that can pre-define a `numpy` array: 
* `numpy.zeros` Return a new array of given shape and type, filled with zeros. 
* `numpy.ones` Return a new array of given shape and type, filled with ones.
* `numpy.empty` Return a new array of given shape and type, without initializing entries.

Let us see what they mean in below. 

In [6]:
# Run me
print('np.zeros')
print(np.zeros(10))
print(np.zeros((2,1)))  # (2, 1) means 2 rows and 1 column
print('np.ones')
print(np.ones(10))
print(np.ones((2,1)))
print('np.empty')
print(np.empty(10))
print(np.empty((2,1)))

np.zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.]
 [0.]]
np.ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1.]
 [1.]]
np.empty
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1.]
 [1.]]


Then we could redefine the entries by reassigning the element. Here is how we do it: 

In [7]:
# Try this
matrix = np.zeros((2,2))
matrix[0,0] = 1    # Reassign the element. 
print(matrix)

[[1. 0.]
 [0. 0.]]


We could also create numpy arrays from files or functions. More information is in [https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html)

If you know the data already, you can use `numpy.array` to initialise the array. For example 
```python
np.array([[1, 0],[0, 0]])
```

In [ ]:
# Try this
np.array([[1, 0],[0, 0]])

### Elementwise Calculation

In most cases by multiplying the lists does not get what we want. This is one of the examples where elementwise calculations are important. For example, we would like to filter all data points that are too large. So we have a filter array 
```python
filter = [0, 0, 0, 0, 1, 0, 1]
```
It means the zero elements are the ones whom should be filtered. So this is the calculation we would like to perform. 
```python
result = [2003*0, 992*0, 102*0, 999*0, 3*1, 9998*0, 5*1]
```
The above code line is an example of elementwise calculation. We can do that in numpy. Firstly, let us look at the documentations in `numpy` and they will tell us what operations we can use. 

We look at these functions from their documentations: 
* [Maths](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)
* [Statistics](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html)
* [Logics](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.logic.html)

So let's do some exercise in below: 

__Exercise:__ Write a code where it will find out the speed of the recorded times. This array represents how fast a class of students has run on 200m runway. The array is given to you. 

Remember that speed is distance divided by time. 

In [ ]:
# Your code
time_finished = np.array([11.8, 12.5, 10.1, 11, 9.8, 1.22, 12.5])
speed = 

In [ ]:
# Solution
time_finished = np.array([11.8, 12.5, 10.1, 11, 9.8, 1.22, 12.5])
speed = np.divide(200, time_finished)
speed

__Exercise:__ What is the mean time of the class? What about the standard deviation?

In [ ]:
# Your code

In [ ]:
# Solution
np.mean(speed)
np.std(speed)

## Pandas Series

<img src="fig/PandasSeries01.png"/>

`pandas` is a library in Python that makes data manipulation easy. It stores data as data frames, which is a spreadsheet format. This week we look into columns of the data frame, which is called __series__. 

To create a series in `pandas`, we use the `pd.Series()` constructor and we put the list data into the brackets. In the following we construct a series called `blue_candles_series`, which represent the monthly sales of blue candles. 

In [4]:
# Try me
import pandas as pd

blue_candles = [1, 3, 2, 1]

blue_candles_series = pd.Series(data=blue_candles)
blue_candles_series

0    1
1    3
2    2
3    1
dtype: int64

You can see above is a series a data from the list `blue_candles`. Which is in the left column, the right column is the index of the data. 

Next we construct another series called `red_candles_series`, which represents the monthly sales of red candles. 

In [5]:
# Try me
import numpy as np
import pandas as pd

red_candles = np.array([1, 2, 5, 0])

red_candles_series = pd.Series(data=red_candles)
red_candles_series

0    1
1    2
2    5
3    0
dtype: int32

We can access the series data as how we access list data. 

In [9]:
red_candles[1]

2

__Exercise:__ How many blue candles sold in second period?

In [ ]:
# Your code below


__Solution:__ 

`blue_candles_series[1]` and we can see there are __3__ of the them sold. 

Before we move on, series can be manipulated. For example we can add the series to get the total sales per month. 

In [8]:
# Try me
total_prod_sold = red_candles_series + blue_candles_series

If you don't see the series shown, change the cell above to make `total_prod_sold` showing. 

## Multidimensional List

Dimensions are different measurements of an object. For example, we can measure boldness as one dimension, on the other hand the happiness of the person. In computer language, dimensions are captured in lists and arrays. We bring in this concept from matrices in mathematics to do so. 

A 1D list is represented by 
```python
[0, 1, 9]
```

A 2D matrix is represented by 
```python
[[0, 1, 9],[1, 2, 0]]
```

As you can see the additional dimensions are nested inside a list. 

__Exercise:__ Covert the matrix below into a list. 

\begin{bmatrix}
1 & 3 \\
0 & 0\\
\end{bmatrix}

In [ ]:
# Your code


__Solution:__
```python
[[1, 3], [0, 0]]
```

The main applications of multi-dimensional lists requires the use of loops. To commit a multi-dimensional loop, we nested them. Let us see an example below: 
```python
a = [...]
for i in range(len(a)): 
    for j in range(len(a[i])): 
        print(j)
```

When it comes to `while` loop, we just need to remember the change in syntax and everything should be easy. Which is the following. 
```python
a = [...]
i = 0
while i < len(a): 
    j = 0
    while j < len(a[i]): 
        print(a[i][j])
        j += 1
    i += 1
```
As you can see, there are 2 counters `i` and `j`. They are initialised just before their loops started. Also remember to increase the counter at the end of each layers. 

__Exercise:__ Write a program where it prints the elements inside the list `ls`.

In [ ]:
ls = [[1, 1], [2, 0], [0]]
# Your code below


In [ ]:
# Solution
ls = [[1, 1], [2, 0], [0]]
for i in range(len(ls)): 
    for j in range(len(ls[i])): 
        print(ls[i][j])
i = 0
while i < len(ls): 
    j = 0
    while j < len(ls): 
        print(ls[i][j])
        j += 1
    i += 1

As you can see the list `ls` has uneven lengths inside each nested lists. So the key above of what you have done, is to make sure the nested loop runs through each nested lists. Rather than hard code the length of each nested lists. 

__Exercise:__ Write a program to convert the list `data` contains some missing data, into a meaningful dataset. They are either shown as `' '` or `'NaN'`. Your task is to convert them into `9999`. 

In [ ]:
data = [[0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1], ['NaN', 2331, 1800, 1999, 2000, 2002, 1996, 2031, 2333, 2201, 1902 ]]
# Your code below


In [11]:
# Solution
data = [[0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1], ['NaN', 'NaN', 'NaN', 1999, 2000, 2002, 1996, 2031, 2333, 2201, ' ']]

i = 0
while i < len(data): 
    j = 0
    while j < len(data[i]): 
        if type(data[i][j]) != int: # Look carefully the data type inside the list. 
            data[i][j] = 9999
        j += 1
    i += 1

print(data)

[[0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1], [9999, 9999, 9999, 1999, 2000, 2002, 1996, 2031, 2333, 2201, 9999]]


__Exercise:__ Write a program to transpose a matrix. For example 
$$
\mathbf{A}\;=\;
\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
$$
then 
\begin{equation}
\mathbf{A}^{T}\;=\;
\begin{bmatrix}
a & c \\
b & d \\
\end{bmatrix}
\end{equation}
Which means for all the elements in the matrix, the row and column number swaps in the new matrix. For example, $b$ in the matrix represents row 1, column 2. It becomes row 2 column 1 in the new matrix. 

The examplar matrix is ready for you. Although you are free to use your own one. 

In [ ]:
A = [[9, -1, 3], [0, 2, 5], [1, 3, 4]]
# Your code below 

In [4]:
# Solution
A = [[9, -1, 3], [0, 2, 5], [1, 3, 4]]
A_transpose = []  # Remember to initialise the list first.

i = 0
while i < len(A): 
    A_transpose.append([])
    j = 0
    while j < len(A[i]): 
        A_transpose[i].append(A[j][i])
        j += 1
    i += 1

print(A_transpose)

[[9, 0, 1], [-1, 2, 3], [3, 5, 4]]


## Conclusion

In today's class we have looked at: 
* Lists and how to manipulate the elements in the list. 
* Difference between lists and arrays. 
* Perform numpy calculations
* Perform operations on a multi-dimensional list. 